name: Create docker package from release

on:  
  push:
#  release:
#    types: created, edited #change to published when ready for production

jobs:
  Test_Github_API:
    runs-on: ubuntu-latest
    name: Test Github API values
    
    steps:
      - name: Github Ref
        id: github_ref
        run: echo "${GITHUB_REF}"
      - name: Fetch API Data 📦
        id: fetch_api_data
        uses: JamesIves/fetch-api-data-action@releases/v1
        with:
          ENDPOINT: https://api.github.com/repos/usaybia/usaybia-data/releases/tags/v0.4-beta
          CONFIGURATION: '{ "method": "GET"}'      
      - name: View API Data
        uses: actions/github-script@v3
        with:
          script: console.log(process.env.FETCH_API_DATA.assets_url)
      - name: View context attributes
        uses: actions/github-script@v3
        with:
          script: console.log(context)
#  Build-and-Push-Docker-Image: # Change the below to use the ${GITHUB_REF} environment variable to get the release tag, see https://www.aaron-powell.com/posts/2021-01-11-using-environments-for-approval-workflows-with-github/
#    runs-on: ubuntu-latest
#    name: Docker Build from Ant relase asset, Tag, Push

#    steps:
#    - uses: actions/upload-artifact@v2
#      with:
#        name: https://api.github.com/repos/usaybia/usaybia-data/releases/tags/${GITHUB_REF}
#        path: path/**/[abc]rtifac?/*
#    - name: Download
#      uses: actions/download-artifact@master
#      with: 
#        name: webpack artifacts
#        path: build
#    - name: Build container image
#      uses: docker/build-push-action@v1
#      with:
#        username: ${{github.actor}}
#        password: ${{secrets.GITHUB_TOKEN}}
#        registry: docker.pkg.github.com
#        repository: usaybia/srophe-exist-app/usaybia-srophe
#        tag_with_sha: true
 #       tags: v0.5
