name: Create docker package from release

on: 
  release:
#  release:
#    types: published

jobs:
  Test_Github_API:
    runs-on: ubuntu-latest
    name: Test Github API values
    
    steps:
      - name: Github Ref
        id: github_ref
        run: echo "${GITHUB_REF}"
