name: Create docker package from release

on:  
  release:
    types: created, edited #change to published when ready for production

jobs:
  Test_Github_API:
    runs-on: ubuntu-latest
    name: Test Github API values
    
    steps:
      - name: Github Ref
        id: github_ref
        run: echo "${GITHUB_REF}"
